// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

var myMap = { };

myMap["Allison"] = 10;

var match = Js_dict.get(peopleAge, "Kevin");

if (match !== undefined) {
  console.log("Kevin is " + String(match));
} else {
  console.log("Kevin is not found");
}

var testRecord = {
  type: "Hey",
  test: "Hello"
};

printTest(testRecord);

var date = new Date();

console.log(date);

console.log(Math.random(23));

console.log(Path.dirname(""));

function difPersonToJs(param) {
  return {
          name: param[/* name */0],
          age: param[/* age */1],
          lastName: param[/* lastName */2]
        };
}

function difPersonFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* age */param.age,
          /* lastName */param.lastName
        ];
}

var pr = difPersonFromJs(getPerson());

console.log(pr[/* name */0]);

exports.myMap = myMap;
exports.testRecord = testRecord;
exports.date = date;
exports.difPersonToJs = difPersonToJs;
exports.difPersonFromJs = difPersonFromJs;
exports.pr = pr;
/*  Not a pure module */
