// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';


var regularList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var regularArray = /* array */[
  1,
  2,
  3
];

console.log(regularList);

console.log(regularArray);

var abc = /* Cons */[
  "s",
  /* Cons */[
    "b",
    /* Cons */[
      "c",
      /* Nil */0
    ]
  ]
];

exports.abc = abc;
exports.regularList = regularList;
exports.regularArray = regularArray;
/*  Not a pure module */
