// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function length(param) {
  if (param) {
    return 1 + length(param[1]) | 0;
  } else {
    return 0;
  }
}

List.sort(Caml_obj.caml_compare, /* :: */[
      7,
      /* :: */[
        2,
        /* :: */[
          4,
          /* :: */[
            5,
            /* [] */0
          ]
        ]
      ]
    ]);

function removeAll(value, _l) {
  while(true) {
    var l = _l;
    if (l) {
      var tail = l[1];
      var head = l[0];
      if (Caml_obj.caml_equal(head, value)) {
        _l = tail;
        continue ;
      } else {
        return /* :: */[
                head,
                removeAll(value, tail)
              ];
      }
    } else {
      return /* [] */0;
    }
  };
}

$$Array.of_list(List.flatten(/* :: */[
          /* :: */[
            2,
            /* :: */[
              3,
              /* :: */[
                4,
                /* [] */0
              ]
            ]
          ],
          /* :: */[
            /* :: */[
              2,
              /* :: */[
                3,
                /* [] */0
              ]
            ],
            /* [] */0
          ]
        ]));

console.log(List.fold_left((function (a, b) {
            return a + b | 0;
          }), 0, /* :: */[
          2,
          /* :: */[
            3,
            /* :: */[
              2,
              /* :: */[
                3,
                /* [] */0
              ]
            ]
          ]
        ]));

var abc = /* Cons */[
  "s",
  /* Cons */[
    "b",
    /* Cons */[
      "c",
      /* Cons */[
        "d",
        /* Nil */0
      ]
    ]
  ]
];

var regularList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.abc = abc;
exports.regularList = regularList;
exports.length = length;
exports.removeAll = removeAll;
/*  Not a pure module */
