// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function make(param) {
  return "";
}

var print = Pervasives.print_string;

exports.print = print;
exports.make = make;
/* No side effect */
