// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Log$MyNewProject = require("./Log.bs.js");

var a = Log$MyNewProject.print("asd");

var LogWithFoo = /* module */[
  /* print */Log$MyNewProject.print,
  /* make */Log$MyNewProject.make,
  /* a */a
];

exports.LogWithFoo = LogWithFoo;
/* a Not a pure module */
