// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Modules$MyNewProject = require("./Modules.bs.js");

console.log(Modules$MyNewProject.$$Math[/* square */2](3));

/*  Not a pure module */
