// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Modules$MyNewProject = require("./Modules.bs.js");

console.log(Modules$MyNewProject.$$Math[/* square */1](3));

/*  Not a pure module */
