// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Arrays$MyNewProject = require("./Arrays.bs.js");

var ArraysToolbox = /* module */[/* checkPangram */Arrays$MyNewProject.isPangram];

var times = Caml_int32.imul;

function square(x) {
  return Caml_int32.imul(x, x);
}

var $$Math = /* module */[
  /* times */times,
  /* square */square
];

console.log(/* () */0);

exports.ArraysToolbox = ArraysToolbox;
exports.$$Math = $$Math;
/*  Not a pure module */
