// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function logFn(a) {
  return (function (prim) {
      console.log(prim);
      return /* () */0;
    });
}

exports.logFn = logFn;
/* No side effect */
